import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..');

async function json(relative) {
  return JSON.parse(await readFile(path.join(root, relative), 'utf8'));
}

test('Stage 0 baseline inventories every retained and planned public capability', async () => {
  const [baseline, registry] = await Promise.all([
    json('registry/stage0-baseline.json'),
    json('registry/capabilities.json'),
  ]);
  const actual = registry.capabilities.map(({ id }) => id).sort();
  const planned = baseline.public_capabilities.map(({ id }) => id).sort();
  assert.equal(actual.length, baseline.baseline_capability_count);
  assert.equal(planned.length, baseline.candidate_capability_count);
  assert.deepEqual(actual, planned.filter((id) => id !== 'frontend-propagation'));
  assert.deepEqual(baseline.acceptance_ids, [
    'acceptance_ui_golden_screen',
    'acceptance_ui_functional',
    'acceptance_ui_visual',
  ]);
});

test('S0-R01: VibeTether repository controls itself with a tracked Project Contract', async () => {
  await access(path.join(root, '.vibetether', 'project.json'));
  const project = await json('.vibetether/project.json');
  assert.equal(project.schema_version, 2);
  assert.equal(project.control_mode, 'team');
});

test('S0-R01: capability status is generated runtime truth rather than a manual snapshot', async () => {
  const status = await readFile(path.join(root, 'docs', 'design', 'VIBETETHER-CONTROL-CAPABILITY-STATUS.md'), 'utf8');
  assert.match(status, /<!-- generated by scripts\/render-capability-status\.mjs; do not edit -->/);
  assert.doesNotMatch(status, /not generated runtime truth/i);
  assert.doesNotMatch(status, /snapshot at commit/i);
});

test('stale status fixture remains explicitly distinguishable from generated truth', async () => {
  const stale = await json('test/fixtures/stage0/stale-status.json');
  assert.equal(stale.generated, false);
  assert.notEqual(stale.source_snapshot, 'd513008');
  const audit = spawnSync(process.execPath, [
    path.join(root, 'scripts', 'audit-stage0-baseline.mjs'),
    '--status', 'test/fixtures/stage0/stale-status.json',
    '--json',
  ], { cwd: root, encoding: 'utf8', windowsHide: true });
  assert.notEqual(audit.status, 0);
  const report = JSON.parse(audit.stdout);
  assert.ok(report.problems.some(({ code }) => code === 'SELF_STATUS_STALE'));
});
