import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { expectedCapabilityStatus } from '../scripts/render-capability-status.mjs';

const root = path.resolve(import.meta.dirname, '..');

async function json(relative) {
  return JSON.parse(await readFile(path.join(root, relative), 'utf8'));
}

test('Stage 0 baseline inventories every retained and planned public capability', async () => {
  const [baseline, registry] = await Promise.all([
    json('registry/stage0-baseline.json'),
    json('registry/capabilities.json'),
  ]);
  const actual = registry.capabilities.map(({ id }) => id).sort();
  const planned = baseline.public_capabilities.map(({ id }) => id).sort();
  const retained = baseline.capability_classification.retained_public.toSorted();
  const candidates = baseline.capability_classification.stage0_candidate_public.toSorted();
  assert.equal(actual.length, baseline.candidate_capability_count);
  assert.equal(planned.length, baseline.candidate_capability_count);
  assert.equal(retained.length, baseline.baseline_capability_count);
  assert.deepEqual(actual, planned);
  assert.deepEqual([...retained, ...candidates].sort(), planned);
  assert.deepEqual(baseline.acceptance_ids, [
    'acceptance_ui_golden_screen',
    'acceptance_ui_functional',
    'acceptance_ui_visual',
  ]);
});

test('S0-R01: VibeTether repository controls itself with a tracked Project Contract', async () => {
  await access(path.join(root, '.vibetether', 'project.json'));
  const project = await json('.vibetether/project.json');
  assert.equal(project.schema_version, 2);
  assert.equal(project.control_mode, 'team');
});

test('S0-R01: capability status is generated runtime truth rather than a manual snapshot', async () => {
  const baseline = await json('registry/stage0-baseline.json');
  const status = await readFile(path.join(root, 'docs', 'design', 'VIBETETHER-CONTROL-CAPABILITY-STATUS.md'), 'utf8');
  assert.equal(status, await expectedCapabilityStatus());
  assert.match(status, /<!-- generated by scripts\/render-capability-status\.mjs; do not edit -->/);
  assert.doesNotMatch(status, /not generated runtime truth/i);
  assert.doesNotMatch(status, /snapshot at commit/i);
  assert.doesNotMatch(status, /\u9225|\uFFFD/u);

  const check = spawnSync(process.execPath, [
    path.join(root, 'scripts', 'render-capability-status.mjs'),
    '--check',
  ], { cwd: root, encoding: 'utf8', windowsHide: true });
  assert.equal(check.status, 0, check.stderr || check.stdout);

  for (const feature of baseline.control_features) {
    for (const relative of feature.evidence) await access(path.join(root, relative));
    assert.ok(status.includes(`| ${feature.label} | ${feature.maturity} |`), feature.id);
  }
  for (const capability of baseline.public_capabilities) {
    assert.ok(status.includes(`| \`${capability.id}\` | ${capability.maturity} |`), capability.id);
  }

  const future = new Map(baseline.control_features.map(({ id, maturity }) => [id, maturity]));
  for (const id of ['decision-memory', 'correction-lifecycle', 'claim-governance', 'host-enforcement', 'failure-replay', 'operator-cockpit']) {
    assert.equal(future.get(id), 'designed', `${id} must remain designed beyond Stage 0`);
  }
  assert.equal(future.get('self-project-contract'), 'implemented');
  assert.match(status, /Decision Memory, Correction, Claim governance, Host Enforcement, Failure Replay, inspect, and the operator cockpit are designed future-stage work/);
});

test('historical delivery records reconcile Stage 0 without rewriting original RED provenance', async () => {
  const records = [
    'docs/superpowers/plans/2026-07-21-vibetether-rc3-hardening.md',
    'docs/superpowers/plans/2026-07-21-vibetether-goal-outcome-coverage.md',
    '.scratch/rc3-hardening/AGENT_DELIVERY.md',
    '.scratch/trustworthy-cockpit/AGENT_DELIVERY.md',
  ];
  for (const relative of records) {
    const source = await readFile(path.join(root, relative), 'utf8');
    assert.equal(source.match(/<!-- stage0-reconciliation-2026-07-22 -->/g)?.length, 1, relative);
    const reconciliation = source.slice(source.indexOf('<!-- stage0-reconciliation-2026-07-22 -->'));
    assert.match(reconciliation, /a71851e98a0b2c00130796a3370c6f5dd86771d2.*historical\/non-current/s, relative);
    assert.match(reconciliation, /implemented later \/ original RED provenance unavailable/, relative);
    assert.match(reconciliation, /Exact current Stage 0 candidate commit: pending final candidate bytes\./, relative);
    assert.match(reconciliation, /STAGE0_COMPLETE remains pending owner acceptance\./, relative);
  }
});

test('stale status fixture remains explicitly distinguishable from generated truth', async () => {
  const stale = await json('test/fixtures/stage0/stale-status.json');
  assert.equal(stale.generated, false);
  assert.notEqual(stale.source_snapshot, 'd513008');
  const audit = spawnSync(process.execPath, [
    path.join(root, 'scripts', 'audit-stage0-baseline.mjs'),
    '--status', 'test/fixtures/stage0/stale-status.json',
    '--json',
  ], { cwd: root, encoding: 'utf8', windowsHide: true });
  assert.notEqual(audit.status, 0);
  const report = JSON.parse(audit.stdout);
  assert.ok(report.problems.some(({ code }) => code === 'SELF_STATUS_STALE'));
});
